#!/usr/bin/env bash
# +----------+------+-----------+----------------------------+-------------+------------+
# | GPU      | GPUs | CPU cores | Node Breakdown             | SBUs/h full | SBUs/h min |
# +----------+------+-----------+----------------------------+-------------+------------+
# | gpu_a100 | 4    | 72        | 1/4 node: 18 cores + 1 GPU | 512 SBUs    | 128 SBUs   |
# | gpu_h100 | 4    | 64        | 1/4 node: 16 cores + 1 GPU | 768 SBUs    | 192 SBUs   |
# | gpu_mig  | 8    | 72        | 1/8 node: 9 cores  + 1 GPU | 512 SBUs    | 64  SBUs   |
# +----------+------+-----------+----------------------------+-------------+------------+
#SBATCH --job-name="PPO_grid"
#SBATCH --time=10:00  # HH:MM:SS
#SBATCH --partition=gpu_a100
#SBATCH --cpus-per-task=18
#SBATCH --gpus-per-node=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --constraint=scratch-node

# Load the required modules
module load 2024
module load Python/3.12.3-GCCcore-13.3.0

# Copy the environment to local scratch storage
declare -r ENV_NAME="l2rpn_case14_sandbox"
mkdir -p "$TMPDIR/envs"
cp -r "$HOME/code/envs/$ENV_NAME" "$TMPDIR/envs/$ENV_NAME"

# Create the output directory
declare -r OUTPUT_STAMP="timestamp$SLURM_JOB_START_TIME-jobid$SLURM_JOB_ID"
declare -r OUTPUT_DIR="$HOME/code/checkpoints/$OUTPUT_STAMP"
mkdir -p "$OUTPUT_DIR"

# Execute the python program
# TODO such low sampling rate for py-spy makes it useless
py-spy record                                    \
    --output "$OUTPUT_DIR/profile"               \
    --format speedscope                          \
    --subprocesses                               \
    --function                                   \
    --rate 1                                     \
    --                                           \
poetry run                                       \
python "$HOME/code/src/ppo.py"                   \
    --env-name "$ENV_NAME"                       \
    --path-env "$TMPDIR/envs"                    \
    --path-checkpoint-save "$TMPDIR/checkpoints" \
    --num-iterations 1

# Copy the saved checkpoints to home
cp -r "$TMPDIR/checkpoints/"* "$OUTPUT_DIR"